//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_codes_org
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_codes_org()
        {
            this.Un_prog_course = new HashSet<Un_prog_course>();
        }
    
        public int Course_code_id { get; set; }
        public string Course_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Un_prog_course> Un_prog_course { get; set; }
    }
}
