//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edcc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edcc_advisingDbContex : DbContext
    {
        public edcc_advisingDbContex()
            : base("name=edcc_advisingDbContex")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course_codes_org> Course_codes_org { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Un_prog_course> Un_prog_course { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Course_codes_edcc> Course_codes_edcc { get; set; }
    }
}
