//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Un_prog_course
    {
        public int ID { get; set; }
        public int un_id { get; set; }
        public int prog_id { get; set; }
        public int course_id { get; set; }
        public int courseType_id { get; set; }
        public int course_code_org_id { get; set; }
        public int course_code_edcc_id { get; set; }
    
        public virtual Course_codes_org Course_codes_org { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual Program Program { get; set; }
        public virtual University University { get; set; }
        public virtual Course_codes_edcc Course_codes_edcc { get; set; }
    }
}
