//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace edccAdvisingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int id { get; set; }
        public string EdccCode { get; set; }
        public string Course1 { get; set; }
        public string SkillSet { get; set; }
    }
}
